#
#
# Kubernetes demo stap 2 
#
# Migratie van nginx naar nieuwere versie 
# 
apiVersion: apps/v1
# ###################################### DEPLOYMENT ######################################
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: nginx
    # ################################## REPLICAS ######################################## 
    replicas: 2
    # ################################## POD #############################################
    template:
        metadata:
            labels:
                app: nginx
    spec:
        containers:
        - name: nginx
          image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
          ports:
          - containerPort: 80
