version: '3'

#   Docker Compose NextCloud YAML 
#   Gemaakt door John Tutert
#   Als basis is gebruikt gemaakt van: 
#   https://github.com/minhng92/odoo-16-docker-compose/blob/master/docker-compose.yml

services:
#
#
#   PostGreSQL
#
#
    db:
        image: postgres:latest
        user: root
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo16@2022      
            - POSTGRES_DB=postgres
        restart: always             # run as a service
        volumes:
            - /home/vagrant/data/odoo/postgresql:/var/lib/postgresql/data
#
#
#   Odoo
#
#
    odoo:
        image: odoo:latest
        user: root
        depends_on:
            - db
        ports:
            - "10016:8069"
            - "20016:8072" # live chat
        tty: true
        command: --
        environment:
            - HOST=db
            - USER=odoo
            - PASSWORD=odoo16@2022
        volumes:
            - /home/vagrant/data/odoo/addons:/mnt/extra-addons
            - /home/vagrant/data/odoo/etc:/etc/odoo
        restart: always             # run as a service
    