apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naam van de deployment
spec:
  selector:
    matchLabels:
      app: nginx # zie label nginx hieronder voor verdere informatie 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec: # Specificatie van de inhoud van iedere POD
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
