#
#   TTTTTT  U    U  TTTTTT  SSSSSS  OOOOOO  FFFFFF  TTTTTT
#     TT    U    U    TT    SS      O    O  FF        TT
#     TT    U    U    TT    SSSSSS  O    O  FFFF      TT
#     TT    U    U    TT        SS  O    O  FF        TT
#     TT    UUUUUU    TT    SSSSSS  OOOOOO  FF        TT
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naam van de deployment
spec:
  selector:
    matchLabels:
      app: nginx # zie label nginx hieronder voor verdere informatie
  replicas: 4 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: nginx
    spec: # Specificatie van de inhoud van iedere POD
      containers:
      - name: nginx
        image: nginx:1.28.2 # Blijf gebruik maken van dezelfde versie als eerdere update
        ports:
        - containerPort: 80
