#
# Saxion HBOICT
#
# Introductie Infrastructuren 
# OICT05 Infrastructuur en ServiceManagement 
# 
# DBMS
#
# Nameserver  192.168.200.254         Windows Server 2019 as Router 
# Nameservers 145.2.14.10 145.2.14.11 Saxion DNS EduRoam
# Nameservers 8.8.88 8.8.4.4          Google 
#
#
# Created by John Tutert
# For Personal or Educational use only
#
# 14 augustus 2024
#
#
network:
    version: 2
    renderer: networkd
    ethernets:
        #
        # NAT
        #
        eth0:
            dhcp4: true
            nameservers:
                addresses:
                # Saxion
                - 145.2.14.10
                - 145.2.14.11
                # Google
                - 8.8.8.8
                - 8.8.4.4
        #
        # Introductie Infrastructuren 
        #
        # Host-Only
        # VMNet3
        #
        eth1:
            dhcp4: false
            addresses:
                - 192.168.200.12/24
            routes: 
                # - to: 0.0.0.0/0
                - to: default
                  via: 192.168.200.254
                # on-link: true
                # metric: 100
            nameservers:
                addresses:
                # Windows Server 2022 as Router
                - 192.168.200.254
                # Saxion
                - 145.2.14.10
                - 145.2.14.11
                # Google
                - 8.8.8.8
                - 8.8.4.4