#
# VAGRANT
#
# DEMO
#
# ANSIBLE
# 
# Netwerk Configuratie 
#
# Ansible Controller IACAM
#
# Versie 12 augustus 2024
#
# Gemaakt door John Tutert
# 
# For Personal and educational use only 
#
network:
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false
      nameservers:
          addresses: [145.2.14.10, 145.2.14.11, 8.8.8.8, 8.8.4.4]
    eth1:
      dhcp4: false
      addresses:
      - 10.1.10.50/24
      gateway4: 10.1.10.1
      nameservers:
          addresses: [10.1.10.1, 145.2.14.10, 145.2.14.11, 8.8.8.8, 8.8.4.4]
      dhcp6: false
  version: 2