version: '3'

#   Docker Compose NextCloud YAML 
#   Gemaakt door John Tutert
#   Als basis is gebruikt gemaakt van: 
#   https://dev.to/natanielchng/a-step-by-step-guide-to-building-your-private-cloud-with-nextcloud-2023-em5

volumes:
    db:
    nextcloud:
#
#
#   Database (MariaDB)
#
#
services:
    db:
        image: mariadb:10.6
        restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=nextcloud
            - MYSQL_PASSWORD=nextcloud
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
#
#
#   NextCloud
#
#
    app:
        image: nextcloud:latest
        restart: always
        ports:
            - 9211:80
        depends_on:
            - db
        volumes:
            - /home/vagrant/data/nextcloud/html:/var/www/html
            - /home/vagrant/data/nextcloud/html/data:/var/www/html/data
        environment:
            - MYSQL_PASSWORD=nextcloud
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=db